"""Initial migration

Revision ID: 37865a7ad63b
Revises: 697083f42a22
Create Date: 2024-08-16 20:30:26.229919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37865a7ad63b'
down_revision = '697083f42a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('read')

    # ### end Alembic commands ###
