"""empty message

Revision ID: e396867efa1f
Revises: efd74c13975d
Create Date: 2024-08-15 22:18:20.003391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e396867efa1f'
down_revision = 'efd74c13975d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('create_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('space_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('space_id', sa.Integer(), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('create_booking', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('space_id')
        batch_op.drop_column('image_url')
        batch_op.drop_column('price')
        batch_op.drop_column('description')
        batch_op.drop_column('location')
        batch_op.drop_column('space_name')

    # ### end Alembic commands ###
